### ISSUE TITLE
Is the Tonizer.py code converting modelities into tokens? 

### ISSUE THREAD

**Issue by Hassaan68** [csuhan/OneLLM#14]
It seems that tokenizer.model is the pretrained SentencePiece model. can we have the access to training code of this model so that we can add training to tokenize more modalities??

**Comment by csuhan** [comment]
tokenizer.model is just fir text processing. For other modalities, we use a conv layer to transform input data into tokens.

**Comment by Hassaan68** [comment]
@csuhan thank you for clarification
