### ISSUE TITLE
Images and videos with high resolution

### ISSUE THREAD

**Issue by codonna9** [csuhan/OneLLM#6]
Thank you for releasing the model & code. Can the model work with images and videos of high resolution like 720x1280, without having to resize them to 224x224?

**Comment by csuhan** [comment]
Hi @codonna9 , Currently we need to resize the image/video to 224. For higher resolution, you can try our [SPHINX](https://github.com/Alpha-VLLM/LLaMA2-Accessory/tree/main/SPHINX) model which supports 448 inputs.

**Comment by codonna9** [comment]
Thanks a lot for your reply. I tried Sphinx before but 448 size is still a bit small for high resolution images/videos

**Comment by csuhan** [comment]
Yeah. It's a trade off between resolution and computation.
