### ISSUE TITLE
Some confusion about the modalities of depth/normal maps.

### ISSUE THREAD

**Issue by laion101** [csuhan/OneLLM#9]
Thank you for your outstanding work. 

I noticed that when running the demo you provided, for QA inference in the modalities of depth/normal maps, it seems essential to provide both the RGB image and the depth/normal maps together to obtain accurate answers. If only the depth/normal information is provided, the system appears unable to respond to questions. 

Could you clarify whether the intended functionality of this system in the depth/normal mode aligns with the paper, which suggests that QA inference can be accomplished solely based on depth/normal information?

<img width="1614" alt="截屏2024-01-05 21 16 08" src="https://github.com/csuhan/OneLLM/assets/155746167/90f5a456-168f-4f4e-b3d9-0469fc17fbdb">
![Uploading WechatIMG5543.jpg…]()

**Comment by laion101** [comment]
<img width="1575" alt="截屏2024-01-05 22 01 59" src="https://github.com/csuhan/OneLLM/assets/155746167/46ea0a60-8234-4d53-9b4f-c514e8e979ff">

**Comment by csuhan** [comment]
Hi @laion101 , currently we need paired depth map and image as input. In general, depth/normal maps serve as auxiliary information for image perception, such as RGBD classification/detection. Therefore we use both RGB images and depth maps as input where depth maps help the model to understand RGB images.

**Comment by laion101** [comment]
Got it, thanks for your reply！
